### ISSUE TITLE
fix: Endpoint aceita solicitações GET em vez de recusá-las conforme a documentação sugere

### ISSUE THREAD

**Issue by rodriguesxxx** [dav1app/broken-mirror#1]
Realizei uma requisição GET em um endpoint que deveria ser usado com POST, conforme indicado na documentação. Recebi como resposta o erro `username or password not provided or invalid.` Decidi testar se o endpoint aceitava um JSON na requisição GET e confirmei isso ao enviar um JSON com `username`: my-username e `password`: 123456789. Como resultado, obtive a resposta de erro esperada: `password is leaked.`

**Comment by dav1app** [comment]
This cannot be considered a bug by itself. There is not a forced method to be used. 

Also, it is often accepted despite `GET with a body` not being a standard. 

Since POST is still working, I'm not considering this one. You can dispute that.
