### ISSUE TITLE
bug: Não está sendo verificado a quantidade de caracteres, sim o tamanho de seus bytes na password.

### ISSUE THREAD

**Issue by rodriguesxxx** [dav1app/broken-mirror#2]
Se forem passados dois desses emojis `😁😁`, totalizando 8 bytes, o sistema retornará o hash normalmente, mesmo essa senha não tendo 8 caracteres. Chego à conclusão de que está sendo verificado o tamanho dessa string (em bytes), não a quantidade de caracteres.

**Comment by dav1app** [comment]
[Fixed](https://github.com/dav1app/broken-mirror/commit/8e911eec839949017e8aa4849309762899e1020c)! This is a critical one. Please send you LN wallet!

**Comment by rodriguesxxx** [comment]
my wallet tearfulgum22@walletofsatoshi.com

**Comment by rodriguesxxx** [comment]
Congratulations on the project, if you need a web dev you can contact me.
