### ISSUE TITLE
Issue: It's possible to use different HTTP verbs to use the API

### ISSUE THREAD

**Issue by viniciusabreusouza** [dav1app/broken-mirror#6]
It was possible to make a DELETE and GET request, not only POST. I don't know if this is the correct behavior expected by you, but I think it is better to limit it to only POST.
Some good practices suggest restrictions on the use of HTTP methods according to the semantics of their operations

![image](https://github.com/dav1app/broken-mirror/assets/4943122/3d7e56dc-a031-41f1-ab44-efddbe20c017)

**Comment by dav1app** [comment]
dup of #1
